apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secretName}}
data:
  jiraServer: "{{.Values.environmentVariables.jiraServer}}"
  jiraToken: "{{".Values.environmentVariables.jiraToken"}}"
  jiraProject: "{{.Values.environmentVariables.jiraProject}}"
  jiraAssignee: "{{.Values.environmentVariables.jiraAssignee}}"
  jiraWatchers: {{.Values.environmentVariables.jiraWatchers}}
  jiraIssueType: "{{.Values.environmentVariables.jiraIssueType}}"
  jiraIssueSummary: "{{.Values.environmentVariables.jiraIssueSummary}}"
  jiraIssueDescNoResponse: "{{.Values.environmentVariables.jiraIssueDescNoResponse}}"
  sharepointClientId: ".Values.environmentVariables.sharepointClientId"
  sharepointClientSecret: "{{.Values.environmentVariables.sharepointClientSecret}}"
  sharepointSiteUrl: "{{.Values.environmentVariables.sharepointSiteUrl}}"
  sharepointFileUrl: "{{.Values.environmentVariables.sharepointFileUrl}}"
  sharepointListTitle: "{{.Values.environmentVariables.sharepointListTitle}}"
  sharepointSheetName: "{{.Values.environmentVariables.sharepointSheetName}}"
  sharepointIdColumn: {{.Values.environmentVariables.sharepointIdColumn}}
  sharepointFnameColumn: "{{.Values.environmentVariables.sharepointFnameColumn}}"
  sharepointLnameColumn: "{{.Values.environmentVariables.sharepointLnameColumn}}"
  sharepointListColumn: "{{.Values.environmentVariables.sharepointListColumn}}"
  sharepointListMaxReturn: {{.Values.environmentVariables.sharepointListMaxReturn}}
  